apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: pact-can-i-deploy
spec:
  stepTemplate:
    env:
    - name: REQUIREMENTS_YAML
      value: "charts/something/requirements.yaml"
    - name: PACT_BROKER_BASE_URL
      value: "https://mentormedier.pactflow.io"
    - name: PACT_BROKER_TOKEN
      valueFrom:
        secretKeyRef:
          key: pactToken
          name: pactbroker
          
    - name: CONSUMER_APP
      value: consumer
    - name: PROVIDER_APP
      value: provider-manager
    - name: HOME
      value: /tekton/home
    name: ""
    resources:
      limits: {}
    workingDir: /workspace/source
  steps:
  - name: can-i-deploy
    image: 523883733847.dkr.ecr.eu-west-1.amazonaws.com/mentor-medier/pipeline-build-tools:0.0.2
    workingDir: /workspace/source
    resources: {}
    script:  |
      #!/usr/bin/env bash
      source .jx/variables.sh
        CONSUMER_VERSION=$(yq eval '.dependencies[] | select(.name=="'${CONSUMER_APP}'").version'  ${REQUIREMENTS_YAML})
      
        PROVIDER_STRING=''
        array=("${PROVIDER_APP}")
        for i in ${array[@]};
        do
          PROVIDER_VERSION=$(yq eval '.dependencies[] | select(.name=="'${i}'").version'  ${REQUIREMENTS_YAML})
          PROVIDER_NAME="${i}"
          PROVIDER_STRING+="--pacticipant=${PROVIDER_NAME} --version=${PROVIDER_VERSION} "
        done
        
        if [[ -z "PROVIDER_STRING" || -z "$CONSUMER_VERSION" ]]; then
            echo "Versions not found for consumer '${CONSUMER_APP}':'$CONSUMER_VERSION' or provider(s) '${PROVIDER_STRING}' "
            exit 1
        else
            echo "Versions found: Provider(s):${PROVIDER_STRING} , Consumer:${CONSUMER_APP} : $CONSUMER_VERSION"
            /pact/bin/pact-broker can-i-deploy --pacticipant=$CONSUMER_APP --version=$CONSUMER_VERSION $PROVIDER_STRING --to-environment=production
        fi
